# Generated by Django 4.1.7 on 2023-04-02 21:01

from django.db import migrations, models
import faker.providers.address
import faker.providers.person


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F1Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=faker.providers.person.Provider.name, max_length=50)),
                ('team', models.CharField(default='Mercedes', max_length=50)),
                ('country', models.CharField(default=faker.providers.address.Provider.country, max_length=50)),
                ('age', models.PositiveIntegerField(default=25)),
                ('podiums', models.PositiveIntegerField(default=72)),
                ('championships', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
